// Generates src/directions/terminal/trace/words5.ts
// Source: dwyl/english-words `words_alpha.txt`
//   https://github.com/dwyl/english-words (public-domain dedication — Unlicense).
// VERIFY at run time: open the repo's LICENSE and confirm it is still
// Unlicense/CC0/public-domain before committing the generated file; record the
// commit SHA you fetched from in the header below. Do NOT proceed if the
// licence is not permissive.
import { writeFileSync } from 'node:fs';

const SRC = 'https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt';

const res = await fetch(SRC);
if (!res.ok) throw new Error(`fetch failed: ${res.status}`);
const raw = await res.text();

const words = [...new Set(
  raw.split(/\r?\n/).map(w => w.trim().toLowerCase())
     .filter(w => /^[a-z]{5}$/.test(w))
)].sort();

if (words.length < 3000) throw new Error(`suspiciously few words: ${words.length}`);

const header =
`// GENERATED by scripts/generate-words5.mjs — do not hand-edit.
// Source: dwyl/english-words words_alpha.txt (public-domain / Unlicense — verified at generation).
// Count: ${words.length} five-letter words.
`;
writeFileSync(
  'src/directions/terminal/trace/words5.ts',
  `${header}export const WORDS5: readonly string[] = ${JSON.stringify(words)};\n` +
  `export const WORD_SET: ReadonlySet<string> = new Set(WORDS5);\n`
);
console.log(`wrote ${words.length} words`);
